In [25]:
import pandas as pd

In [26]:
train_data = pd.read_csv("train_data.txt",sep=":::", engine="python", header=None)
train_data.head()

,0,1,2,3
0,1,Oscar et la dame rose (2009),drama,Listening in to a conversation between his do...
1,2,Cupid (1997),thriller,A brother and sister with a past incestuous r...
2,3,"Young, Wild and Wonderful (1980)",adult,As the bus empties the students for their fie...
3,4,The Secret Sin (1915),drama,To help their unemployed father make ends mee...
4,5,The Unrecovered (2007),drama,The film's title refers not only to the un-re...

In [27]:
train_data.shape

(16015, 4)

In [28]:
train_data.head()

,0,1,2,3
0,1,Oscar et la dame rose (2009),drama,Listening in to a conversation between his do...
1,2,Cupid (1997),thriller,A brother and sister with a past incestuous r...
2,3,"Young, Wild and Wonderful (1980)",adult,As the bus empties the students for their fie...
3,4,The Secret Sin (1915),drama,To help their unemployed father make ends mee...
4,5,The Unrecovered (2007),drama,The film's title refers not only to the un-re...

In [29]:
import pandas as pd

In [30]:
train_data = pd.read_csv("train_data.txt",sep=":::", engine="python", header=None)

In [31]:
!1s

/bin/bash: line 1: 1s: command not found

In [32]:
train_data = pd.read_csv("train_data.txt",sep=":::", engine="python", header=None)

In [33]:
train_data.head()

,0,1,2,3
0,1,Oscar et la dame rose (2009),drama,Listening in to a conversation between his do...
1,2,Cupid (1997),thriller,A brother and sister with a past incestuous r...
2,3,"Young, Wild and Wonderful (1980)",adult,As the bus empties the students for their fie...
3,4,The Secret Sin (1915),drama,To help their unemployed father make ends mee...
4,5,The Unrecovered (2007),drama,The film's title refers not only to the un-re...

In [34]:
train_data.shape

(16015, 4)

In [35]:
train_data.head()

,0,1,2,3
0,1,Oscar et la dame rose (2009),drama,Listening in to a conversation between his do...
1,2,Cupid (1997),thriller,A brother and sister with a past incestuous r...
2,3,"Young, Wild and Wonderful (1980)",adult,As the bus empties the students for their fie...
3,4,The Secret Sin (1915),drama,To help their unemployed father make ends mee...
4,5,The Unrecovered (2007),drama,The film's title refers not only to the un-re...

In [36]:
train_data.columns

Index([0, 1, 2, 3], dtype='int64')

In [37]:
train_data.columns = ["id", "title", "genre", "text"]

In [38]:
train_data.head()

,id,title,genre,text
0,1,Oscar et la dame rose (2009),drama,Listening in to a conversation between his do...
1,2,Cupid (1997),thriller,A brother and sister with a past incestuous r...
2,3,"Young, Wild and Wonderful (1980)",adult,As the bus empties the students for their fie...
3,4,The Secret Sin (1915),drama,To help their unemployed father make ends mee...
4,5,The Unrecovered (2007),drama,The film's title refers not only to the un-re...

In [39]:
from sklearn.feature_extraction.text import TfidfVectorizer
tfid = TfidfVectorizer(max_features=5000)
X = tfid.fit_transform(train_data["text"])
print(X.shape)

(16015, 5000)

In [40]:
y = train_data["genre"]
print(y.head())

0        drama
1     thriller
2        adult
3        drama
4        drama
Name: genre, dtype: object

In [41]:
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=42)
print(X_train.shape)
print(X_test.shape)

(12812, 5000)
(3203, 5000)

In [42]:
from sklearn.naive_bayes import MultinomialNB
model = MultinomialNB()
model.fit(X_train, y_train)
print("Model Trained Sucessfully!")

Model Trained Sucessfully!

In [43]:
from sklearn.metrics import accuracy_score
y_pred = model.predict(X_test)
accuracy = accuracy_score(y_test, y_pred)
print("Accuracy:", accuracy)

Accuracy: 0.4661255073368717

In [44]:
print("Movie Genre Classification Accuracy:", accuracy*100, "%")

Movie Genre Classification Accuracy: 46.61255073368717 %